name: update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - name: setup git
        run: |
          git config user.name "iptv-bot[bot]"
          git config user.email "84861620+iptv-bot[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v3
        if: ${{ !env.ACT }}
        with:
          node-version: 18
          cache: 'npm'
      - name: install dependencies
        run: npm install
      - name: update internal playlists
        run: npm run playlist:update --silent >> $GITHUB_OUTPUT
        id: playlist-update
      - name: check internal playlists
        run: |
          npm run playlist:lint
          npm run playlist:validate
      - name: generate public playlists
        run: npm run playlist:generate
      - name: generate .api/streams.json
        run: npm run api:generate
      - name: update readme.md
        run: npm run readme:update
      - run: git status
      - name: commit changes to /streams
        run: |
          git add streams
          git status
          git commit --allow-empty -m "[Bot] Update /streams" -m "Committed by [iptv-bot](https://github.com/apps/iptv-bot) via [update](https://github.com/Navezjt/iptv/actions/runs/${{ github.run }}) workflow." -m "${{ steps.playlist-update.outputs.OUTPUT }}" --no-verify
      - name: commit changes to readme.md
        run: |
          git add README.md
          git status
          git commit --allow-empty -m "[Bot] Update README.md" -m "Committed by [iptv-bot](https://github.com/apps/iptv-bot) via [update](https://github.com/Navezjt/iptv/actions/runs/${{ github.run }}) workflow." --no-verify
      - name: push all changes to the repository
        if: ${{ !env.ACT && github.ref == 'refs/heads/master' }}
        run: git push
      - name: deploy public playlists to github pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: ${{ !env.ACT && github.ref == 'refs/heads/master' }}
        with:
          repository-name: Navezjt/iptv
          branch: gh-pages
          folder: .gh-pages
          git-config-name: iptv-bot[bot]
          git-config-email: 84861620+iptv-bot[bot]@users.noreply.github.com
          commit-message: '[Bot] Deploy to GitHub Pages'
          clean: true
      - name: move .api/streams.json to Navezjt/api
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        if: ${{ !env.ACT && github.ref == 'refs/heads/master' }}
        with:
          repository-name: Navezjt/api
          branch: gh-pages
          folder: .api
          git-config-name: iptv-bot[bot]
          git-config-email: 84861620+iptv-bot[bot]@users.noreply.github.com
          commit-message: '[Bot] Deploy to Navezjt/api'
          clean: false
